# Azure DevOps Pipeline - Assignment
# Simple pipeline to checkout code from GitHub and list repository contents

trigger:
- main
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout code from GitHub repository'

- script: |
    echo "Repository contents:"
    ls -la
  displayName: 'List repository contents'
