runtime: "java17"
service: "default"

env: "flex"

handlers:
  - url: "/.*"
    script: "this field is required, but ignored"

manual_scaling:
  instances: 1

#env_variables:
#  ENCRYPT_KEY: "your_encryption_key_here"
#  DB_URL: "jdbc:mysql://34.130.13.64/visa_database?cloudSqlInstance=visa-database-api:northamerica-northeast2:visa-api-database&socketFactory=com.google.cloud.sql.mysql.SocketFactory"
#  DB_PASSWORD: "Ismael1103"
#  DB_USERNAME: "root"